# This configuration describe the appium want
test_devices:
  - platformName: "Android"
    platformVersion: "11.0"
    deviceName: "154614230400AQL"
    appPackage: "com.iflytek.inputmethod.imehook"
    appActivity: "com.iflytek.inputmethod.imehook.MainActivity"
    newCommandTimeout: "8000"
    systemPort: 8200
    noReset: False
    port: 4000
    udid: "154614230400AQL"
    iflytekPort: "8888"
    brand: 4
    read_file_path: "test02"
    keyboard_type: 2
    test_type: 4
  - platformName: "Android"
    platformVersion: "7.1.2"
    deviceName: "127.0.0.1:62025"
    appPackage: "com.iflytek.inputmethod.imehook"
    appActivity: "com.iflytek.inputmethod.imehook.MainActivity"
    newCommandTimeout: "8000"
    systemPort: 8201
    noReset: False
    port: 4001
    udid: "127.0.0.1:62025"
    iflytekPort: "8888"
    brand: 3
    read_file_path: "test02"
    keyboard_type: 2
    test_type: 4
  - platformName: "Android"
    platformVersion: "11.0.0"
    deviceName: "faa77721"
    appPackage: "com.iflytek.inputmethod.imehook"
    appActivity: "com.iflytek.inputmethod.imehook.MainActivity"
    newCommandTimeout: "8000"
    systemPort: 8202
    noReset: False
    port: 4002
    udid: "faa77721"
    iflytekPort: "8888"
    brand: 4
    read_file_path: "test01"
    keyboard_type: 1
    test_type: 1
  - platformName: "Android"
    platformVersion: "7.1.2"
    deviceName: "127.0.0.1:62027"
    appPackage: "com.iflytek.inputmethod.imehook"
    appActivity: "com.iflytek.inputmethod.imehook.MainActivity"
    newCommandTimeout: "8000"
    systemPort: 8203
    noReset: False
    port: 4002
    udid: "127.0.0.1:62027"
    iflytekPort: "8888"
    brand: 3
    read_file_path: "test04"
    keyboard_type: 1
    test_type: 1
